domain:
  name: Pastebin.com
  description: Text storage site
  actors:
    client:
      name: Client
      description: Users are using internet (HTTPs) to connect
      relations:
        - calls - dns
        - calls - cdn
        - calls - load-balancer
        - calls - pastebin
  systems:
    dns:
      name: Domain Name System
      description: One of the industry-standard suite of protocols that comprise TCP/IP, and together the DNS Client and DNS Server provide computer name-to-IP address mapping name resolution services to computers and users
    pastebin:
      name: Pastebin
      description: A type of online content-hosting service where users can store plain text (e.g. source code snippets for code review via Internet Relay Chat (IRC))
      containers:
        analytics:
          name: Analytics
          description: Collect statistics about saved texts
          relations:
            - get information from - object-store
            - save analytics data - analytics-db
          components:
            analytics--app:
              name: Analytics service
              description: Check storage and save stats
              relations:
                - check storage - object-store--bucket
                - save stats - analytics-db--main
        analytics-db:
          name: Analytics DB
          description: Stats information
          components:
            analytics-db--main:
              name: Main schema
              description: Store stats about object store
        cdn:
          name: Content delivery network
          description: A network of interconnected servers that speeds up webpage loading for data-heavy applications
          relations:
            - read text - object-store
        load-balancer:
          name: Load Balancer
          description: Distribute network traffic equally across a pool of resources that support an application
          relations:
            - forward - web-server
        memory-cache:
          name: Memory cache
          description: Useful for handling the unevenly distributed traffic and traffic spikes
        object-store:
          name: Object store
          description: Store text
          components:
            object-store--bucket:
              name: Main bucket
              description: Store pasted texts
        read-api:
          name: Read API
          description: Check provided link and return text
          relations:
            - read url - sql-db
            - read saved text - object-store
            - uses - memory-cache
          components:
            read-api--app:
              name: Read API service
              description: Check url and provide text
              relations:
                - check url - sql-db--main
                - read pasted text if url exists - object-store--bucket
        sql-db:
          name: Url database
          description: Store map beyween url and path of text
          components:
            sql-db--main:
              name: Main schema
              description: Store url, expiration, creation time and path
        web-server:
          name: PasteBin app
          description: Allows to store plain text (support editing and versioning)
          relations:
            - save text - write-api
            - read text - read-api
          components:
            web-server--app:
              name: PasteBin service
              description: Forward requests to proper API services
              relations:
                - save text - write-api--app
                - read text - read-api--app
        write-api:
          name: Write API
          description: Generate a unique url, save pasted text
          relations:
            - save url and path - sql-db
            - save text - object-store
          components:
            write-api--app:
              name: Write API service
              description: Generate a unique url, save pasted text
              relations:
                - write created url and path - sql-db--main
                - save pasted text - object-store--bucket
views:
  main:
    elements:
      analytics:
        x: 500
        y: 375
        relations:
          save analytics data - analytics-db: []
          get information from - object-store:
            - x: 500
              y: 550
      analytics-db:
        x: 400
        y: 475
      cdn:
        x: 360
        y: 175
        relations:
          read text - object-store:
            - x: 362
              y: 398
      client:
        x: 200
        y: 75
        relations:
          calls - cdn: []
          calls - load-balancer: []
      load-balancer:
        x: 200
        y: 175
        relations:
          forward - web-server: []
      memory-cache:
        x: 200
        y: 475
      object-store:
        x: 300
        y: 575
      pastebin:
        x: 300
        y: 365
      read-api:
        x: 300
        y: 375
        relations:
          uses - memory-cache: []
          read saved text - object-store: []
          read url - sql-db:
            - x: 285
              y: 525
      sql-db:
        x: 100
        y: 575
      web-server:
        x: 200
        y: 275
        relations:
          read text - read-api: []
          save text - write-api: []
      write-api:
        x: 100
        y: 375
        relations:
          save text - object-store:
            - x: 125
              y: 525
          save url and path - sql-db: []
  top-level:
    elements:
      client:
        x: 250
        y: 75
        relations:
          calls - dns: []
          calls - pastebin: []
      dns:
        x: 350
        y: 175
      pastebin:
        x: 150
        y: 175
